// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyEczrzI0BQzKahAy90utG1hCoyO7Yl3E',
    appId: '1:532221798335:web:7529515a31f4bed1c5230a',
    messagingSenderId: '532221798335',
    projectId: 'chat-demo-169f8',
    authDomain: 'chat-demo-169f8.firebaseapp.com',
    storageBucket: 'chat-demo-169f8.appspot.com',
    measurementId: 'G-5N98N02LCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6nzen9etMz1N0UPXbp0i1qIQV2CoyN50',
    appId: '1:532221798335:android:e5020c0b42a0ac8ac5230a',
    messagingSenderId: '532221798335',
    projectId: 'chat-demo-169f8',
    storageBucket: 'chat-demo-169f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUThkc0DI0EJXb-Yqje5wss7zA4c_2irg',
    appId: '1:532221798335:ios:4d326cd82666b82bc5230a',
    messagingSenderId: '532221798335',
    projectId: 'chat-demo-169f8',
    storageBucket: 'chat-demo-169f8.appspot.com',
    iosClientId: '532221798335-igm4insk1s7581pmdv7033pijfbdqisp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUThkc0DI0EJXb-Yqje5wss7zA4c_2irg',
    appId: '1:532221798335:ios:4d326cd82666b82bc5230a',
    messagingSenderId: '532221798335',
    projectId: 'chat-demo-169f8',
    storageBucket: 'chat-demo-169f8.appspot.com',
    iosClientId: '532221798335-igm4insk1s7581pmdv7033pijfbdqisp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyEczrzI0BQzKahAy90utG1hCoyO7Yl3E',
    appId: '1:532221798335:web:52c7da44ecd9a06dc5230a',
    messagingSenderId: '532221798335',
    projectId: 'chat-demo-169f8',
    authDomain: 'chat-demo-169f8.firebaseapp.com',
    storageBucket: 'chat-demo-169f8.appspot.com',
    measurementId: 'G-XHLPC74TJR',
  );
}
